### PR TITLE
Add upgrade script

### PR DESCRIPTION
**Pull request by alexole**

### CODE REVIEW

**Comment by jankatins** [comment]
I haven't run the makefile, but I think the right fix would be to readd the makefile rule for creating the last upgrade script from the full script in build/ and the part from the rpm generation to overwrite the last script:

Before 861aaf74afb2c0160143e5480465fff46967e181

- Add the noop for the latest step (which got not used during this release, but the next)
- The makefile creates the same script but in build/
- The rpm creates the archive (with the noop script in it) and the rpm step then overwrites the script with the one form build/
- (when the next release is cut, the noop from this time is used as a step to the then generated full upgrade)

Now the script is empty, so the actual scripts/functions will not be (re-)created and therefore not the new function.

So from my perspective, it's either bringing back the build/ area (for overwriting the noop in the last upgrade step) or actually using the upgrade scripts as upgrades by letting them only contain the changes (now that PG 10+ does not need a full script as `<name>-<version>.sql` anymore).

**Comment by alexole** [comment]
I already moved the PR to draft, also realized it will not work as as.

**Comment by alexole** [comment]
Well, I think, for now easiest would be to just copy the file `aiven_extras.sql` to `aiven_extras--1.1.7--1.1.8.sql`, but yes, this part got broken a bit.

**Comment by jankatins** [comment]
IMO looks good.

Maybe add a check+failure message that an upgrade script ending in the last version exists: `sql/aiven_extras--*--$(last_ver).sql` -> that way there would be no way to forget to manual add the required upgrade path element... (or do some magic and parse out the even older version from the last existing upgrade script and add a noop...)

Untested:

```
sql/aiven_extras--$(last_ver)--$(short_ver).sql: sql/aiven_extras.sql
	mkdir -p $(@D)
	cp -fp $^ $@
ifeq ("$(wildcard sql/aiven_extras--*--$(last_ver).sql)","")
	@echo "ERROR: missing upgrade script to last version (sql/aiven_extras--*--$(last_ver).sql)"
	@echo "       -> Please add one (with only --NOOP in it) and commit it
	@false   
endif
```

**Comment by alexole** [comment]
Thanks for a suggestion @jankatins , I think that is good for now. We should think about a better approach.

**Review by kmichel-aiven — APPROVED** [review]

**Pull request merged**
