### PR TITLE
Bump version to 1.1.8

### PR DESCRIPTION
**Pull request by alexole**

### CODE REVIEW

**Review by packi — APPROVED** [review]
LGTM

**Comment by jankatins** [comment]
This probably needs a upgrade file: sql/aiven_extras--1.1.7--1.1.8.sql (with noop, I would guess)

**Comment by alexole** [comment]
Hey @jankatins long time no see :) I hope you are doing great
As for the comment - not anymore, now `/usr/pgsql-*/share/extension/aiven_extras--1.1.8.sql` is going to be generated and installed automatically and this should include upgrade path for any version

**Comment by jankatins** [comment]
https://www.postgresql.org/docs/current/extend-extensions.html#id-1.8.3.20.15 says the reverse: the current version script is not needed anymore on pg 10, only the upgrade part scripts name-x--y.sql.

> An extension that has been around for awhile will probably exist in several versions, for which the author will need to write update scripts. For example, if you have released a foo extension in versions 1.0, 1.1, and 1.2, there should be update scripts foo--1.0--1.1.sql and foo--1.1--1.2.sql. Before PostgreSQL 10, it was necessary to also create new script files foo--1.1.sql and foo--1.2.sql that directly build the newer extension versions, or else the newer versions could not be installed directly, only by installing 1.0 and then updating. That was tedious and duplicative, but now it's unnecessary, because CREATE EXTENSION can follow update chains automatically. For example, if only the script files foo--1.0.sql, foo--1.0--1.1.sql, and foo--1.1--1.2.sql are available then a request to install version 1.2 is honored by running those three scripts in sequence. The processing is the same as if you'd first installed 1.0 and then updated to 1.2. (As with ALTER EXTENSION UPDATE, if multiple pathways are available then the shortest is preferred.) Arranging an extension's script files in this style can reduce the amount of maintenance effort needed to produce small updates.

Up to the reorg of the makefile, the last step was autogenerated to have the full install script content (allowing the rest of the upgrade scripts to be empty). Now the last step is completely missing and my guess would be that an upgrade of aiven_extra from the last version to this one will fail.

**Comment by alexole** [comment]
Oops, I think you are right. Thanks for watching the PR after even leaving ;)

**Pull request merged**
